---
title: "Project_File_Z_G"
format: html
editor: visual
---

```{r}
#| include: FALSE
library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
library(httr)
library(httr2)
library(janitor)
```

## Penguin Random House Web Scraping

```{r}
#Download SelectorGadget to browser
#Step 0: Check if the website allows scraping + making sure to do it in a friendly manner
robotstxt::paths_allowed("https://www.penguinrandomhouse.com/authors/events/")

#Create a function to find individual information from the events page
info_from_page <- function(event, css_selector) {
#Read the URL containing event data and turn the html code into an XML
  read_html(event) |> 
#Extracting nodes from the XML by using the CSS path from selector
    html_nodes(css_selector) |> 
#Extracting text
    html_text()
}

#Test, event page and the date
info_from_page("https://www.penguinrandomhouse.com/authors/events/", ".date-display")
```

```{r}
scrape_events <- function(url) {
    Sys.sleep(2)
    event_date <- info_from_page(url, ".start")
    event_book <- info_from_page(url, ".author-of a")
    event_author <- info_from_page(url, ".author-name:nth-child(1)")
    event_host <- info_from_page(url, ".event-location .hdr")
    event_state <- info_from_page(url, "span:nth-child(4)")
    options(timeout = 700)
    
    tibble(date = event_date, 
           book = event_book, 
           author = event_author,
           host = event_host,
           state = event_state
    )
}
```

```{r}
scrape_events("https://www.penguinrandomhouse.com/authors/events/?page=2")
```
```{r}
scrape_events <- function(url){
  
  date <- info_from_page(url, ".start")
  book <- info_from_page(url, ".author-of a")
  author <- info_from_page(url, ".author-name:nth-child(1)")
  host <- info_from_page(url, ".event-location .hdr")
  state <- info_from_page(url, "span:nth-child(4)")
  zip_code <- info_from_page(url, "span:nth-child(5)")
  
  tibble(date = date, 
           book = book, 
           author = author,
           host = host,
           state = state)
  
}
```

```{r}
for(i in c(10, 11, 12, 1, 2, 3, 4)){
  for(j in 1:31){
    date = str_c(i, "/", j, "/", "2024")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    scrape_events(url)
  }
}
```

```{r}
i=11
j=1
date = str_c(i, "/", j, "/", "2024")
url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
scrape_events(url)
```

```{r}
october <- list()
  i=10
for(j in 23:31){
    date = str_c(i, "/", j, "/", "2024")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    october[[j]] <- scrape_events(url)
}
  
  october_tibble <- bind_rows(october) |> 
  as.tibble()
  
november <- list()
  i=11
for(j in 1:30){
    date = str_c(i, "/", j, "/", "2024")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    november[[j]] <- scrape_events(url)
}
  
  november_tibble <- bind_rows(november) |> 
    as.tibble()
  
december <- list()
  i=12
for(j in 1:31){
    date = str_c(i, "/", j, "/", "2024")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    december[[j]] <- scrape_events(url)
}
  
  december_tibble <- bind_rows(december) |> 
    as.tibble()
```

```{r}
events <- rbind(october_tibble,
                 november_tibble,
                 december_tibble,
                 january_tibble,
                 february_tibble,
                 march_tibble,
                 april_tibble)
events
```


```{r}
january <- list()
  i=1
for(j in 1:31){
    date = str_c(i, "/", j, "/", "2025")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    january[[j]] <- scrape_events(url)
}
  
january_tibble <- bind_rows(january) |> 
as.tibble()

february <- list()
  i=2
for(j in 1:28){
    date = str_c(i, "/", j, "/", "2025")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    february[[j]] <- scrape_events(url)
}
  
  february_tibble <- bind_rows(february) |> 
    as.tibble()
  
march <- list()
  i=3
for(j in 1:31){
    date = str_c(i, "/", j, "/", "2025")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    march[[j]] <- scrape_events(url)
}
  
  march_tibble <- bind_rows(march) |> 
    as.tibble()
  
april <- list()
  i=4
for(j in 1:30){
    date = str_c(i, "/", j, "/", "2025")
    url = str_c("https://www.penguinrandomhouse.com/authors/events/?datefrom=", date, "&dateto=", date)
    april[[j]] <- scrape_events(url)
}
  
april_tibble <- bind_rows(april) |> 
as.tibble()
```
